# Generated by Django 3.2.5 on 2021-08-09 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_bet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='score_one',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bet',
            name='score_two',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='score_one',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='score_two',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
