# Generated by Django 3.2.5 on 2021-08-10 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210809_1843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bet',
            old_name='score_one',
            new_name='score1',
        ),
        migrations.RenameField(
            model_name='bet',
            old_name='score_two',
            new_name='score2',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='score_one',
            new_name='score1',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='score_two',
            new_name='score2',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='team_one',
            new_name='team1',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='team_two',
            new_name='team2',
        ),
    ]
